name: Deploy UI to GitHub Pages
on:
  push:
    branches: [ main ]
    paths:
      - 'ui/**'
      - '.github/workflows/deploy-ui.yml'
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: 'pages'
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ui
      - uses: actions/deploy-pages@v4
